### PR TITLE
Add autoreload feature

### PR DESCRIPTION
**Pull request by hadalin**

### CODE REVIEW

**Comment by kostko** [comment]
Can you elaborate on why you moved the greenlet monkeypatching further down?

**Comment by kostko** [comment]
Otherwise LGTM, just that I would always bump the version in a separate commit.

**Comment by hadalin** [comment]
> Can you elaborate on why you moved the greenlet monkeypatching further down?

Moved imports at the top because of [PEP8](http://legacy.python.org/dev/peps/pep-0008/#imports).

**Comment by kostko** [comment]
The idea was that monkey patching is done before any of Django is imported. But since we also handle that in `manage.py` it is probably not so problematic as otherwise, such a move would actually break functionality.

**Pull request merged**
